### ISSUE TITLE
3.1UIView修正のお願い

### ISSUE THREAD

**Issue by xxminamixx** [mixi-inc/iOSTraining#14]
現在、iOS開発の学習で本チュートリアルを使わせていただいている者ですが、以下の点に気付きましたので、修正頂けると幸いです。

3.1UIView
大見出しUIViewをコード上で利用する　の下部
原文：viewを追加するにはaddSubViewを利用します。
修正：viewを追加するにはaddSubviewを利用します。

原文：[self.view addSubView:view]; // viewを追加. self.viewはUIViewControllerのプロパティ
修正：[self.view addSubview:view]; // viewを追加. self.viewはUIViewControllerのプロパティ

addSubviewの"v"が大文字になっている点に気が付きました。
よろしくお願いいたします。

**Comment by punchdrunker** [comment]
ご指摘ありがとうございます。対応しました。
https://github.com/mixi-inc/iOSTraining/wiki/3.1-UIView/_compare/8f7a3363bacb6a03d63706822d4b0e82cc2b6b7d...447aa1c13deffc6ccff9dbdf9e84c59493e23253

**Comment by xxminamixx** [comment]
@punchdrunker 確認いたしました。早急な対応ありがとうございます。
